### ISSUE TITLE
Some test cases in panic_safety seem confusing

### ISSUE THREAD

**Issue by panoob** [sslab-gatech/Rudra#54]
Hi there, I have read the original SOSP21 paper, but I still don't understand the intentions of test cases under [panic_safety] folder.

Specifically, why is the function in  `order_safe.rs` regarded as safe compared to the one in `order_unsafe.rs`? Is there any panics before the fix-up for unsafe code?

```
fn test_order_safe<I: Iterator<Item = impl Debug>>(mut iter: I) {
    println!("{:?}", iter.next());
    unsafe {
        std::ptr::read(1234 as *const i32);
    }
}
```

```
fn test_order_unsafe<I: Iterator<Item = impl Debug>>(mut iter: I) {
    unsafe {
        std::ptr::read(&Box::new(1234) as *const _);
    }
    println!("{:?}", iter.next());
}
```

Thanks

**Comment by Qwaz** [comment]
Panic safety bug involves three actions.
1. Unsafe lifetime bypass
2. Function call that may panic
3. Fixup for the bypass

Rudra's panic safety checker reports an error if there is a flow from action 1 to action 2. In the presented test cases, `std::ptr::read` corresponds to action 1 and `iter.next()` corresponds to action 2. Both tests intentionally do not involve any real undefined behavior in order to not break Rust's parallel testing ability. In a more realistic case, action 3 would be included in the code such as `std::mem::forget` in the code.

If you are interested in reproducing actual bugs with Rudra, please refer to ["Reproduce Bugs found by Rudra" section](https://github.com/sslab-gatech/Rudra-Artifacts#reproduce-bugs-found-by-rudra-20-human-minutes--60-compute-minutes) in the artifact repository.

**Comment by kynehc** [comment]
Thanks for your detailed explanation. I understood the definition of a panic safety bug in the paper. My confusion regarding the test case is whether the function call iter.next() will panic.

I learned from the implementation of `Iterator.next()` in the std library that it will not panic, as mentioned in https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#tymethod.next. Is it because in older versions of the Rust std library, iter.next() may panic? Or are you concerned about iterators customized by developers that might panic?

Thanks again

**Comment by Qwaz** [comment]
`Iterator` is a trait, and any type that implements `Iterator` trait can choose whatever implementation they like for `Iterator::next`. `Iterator::next` doesn't have a default implementation, so I'm not sure what you are referring to by `iter.next()` in the standard library.
